kas-lab/suave

.github/workflows/main.yml

action only trigger by push to main or PR

👷 action on push to master and PR only

---

launch/simulation.launch.py

Add launchfile to start simulation

✨ Add launchfile to start simulation

---

CMakeLists.txt
launch/pipeline_env.launch.py
scripts/lawn_mower.py

Lawn mower patch

---

scripts/spiral_pattern_position.py

Reduce rate that setpoints are being published.

Reduce rate that setpoints are being published

---

CMakeLists.txt
launch/simulation.launch.py
scripts/follow_pipeline.py
scripts/pipeline_node.py

Robot follows the pipeline if it is detected.
First it is necessary to start the simulation + ardusub sitl + pipeline_node. Then the spiral_patter_position_node is started, and when the pipeline is detected the spiral node can be killed and the follow_pipeline node can be started.

Following pipeline working

---

pipeline_inspection_metacontrol/config/pipeline_inspection.owl

Added requireby relation to cc_thruster_2. Not every component has requireby relations added, since the structure might changed, as discussed in the mros teams channel.

added requireby relation to one component

---

pipeline_inspection_metacontrol/launch/metacontrol.launch.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/water_visibility_observer.py
pipeline_inspection_metacontrol/setup.py

Add water visibility observer. Closes #42

✨ add water_visibility_observer node

---

pipeline_inspection/launch/simulation.launch.py
pipeline_inspection/pipeline_inspection/bluerov_gazebo.py
pipeline_inspection/pipeline_inspection/follow_pipeline.py
pipeline_inspection_metacontrol/config/simple_system_modes.yaml
pipeline_inspection_metacontrol/launch/metacontrol.launch.py
pipeline_inspection_metacontrol/launch/pipeline_inspection_metacontrol.launch.py
pipeline_inspection_metacontrol/launch/system_modes.launch.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/follow_pipeline_lc.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/pipeline_metacontrol_node.py
pipeline_inspection_metacontrol/setup.py

Add a follow pipeline as lifecycle node 
Changes to launchfiles

Follow pipeline as lifecycle node and changes to launchfiles

---

pipeline_inspection_metacontrol/config/pipeline_inspection.owl

remove component state from owl

🔥 remove component state from owl

---

pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/water_visibility_observer.py

Start water visibility observer when mode is set to GUIDED.
Closes #74

✨ Start water visibility observer when GUIDED

---

README.md
pipeline_inspection/launch/simulation.launch.py
pipeline_inspection/pipeline_inspection.rosinstall
pipeline_inspection/pipeline_inspection/bluerov_gazebo.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/const_dist_mission.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/time_constrained_mission.py

Closes #80. I think we should not change z since it doesnt change anything in the mission. I am also saving x and y in the results file, but the way i implemented it is that the bluerov gazebo node fetches the first position received from gazebo and marks that as the initial pos, but the robot is drifting a bit so the initial pos is slightly wrong. I will try to find a better way to save this.
I upgraded mavros to 2.4.0
And ardusub to ArduSub-4.1.1

Bluerov position as param and mavros + ardusub upgrade

---

README.md
pipeline_inspection/launch/pipeline_inspection.launch.py
pipeline_inspection_metacontrol/launch/const_distance_mission_no_adapt.launch.py
pipeline_inspection_metacontrol/launch/time_constrained_mission.launch.py
pipeline_inspection_metacontrol/launch/time_constrained_mission_no_adapt.launch.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/const_dist_mission.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/const_dist_mission_no_adapt.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/time_constrained_mission.py
pipeline_inspection_metacontrol/pipeline_inspection_metacontrol/time_constrained_mission_no_adapt.py
pipeline_inspection_metacontrol/setup.py

Add missions with no adaptation. I'm not really proud of how it's done, but I just wanted to get it done quickly. I will create an enhancement issue to refactor all mission files
Closes #84. Closes #85.

Add missions with no adaptation

---

suave_metacontrol/launch/suave_random.launch.py
suave_metacontrol/package.xml
suave_metacontrol/setup.py
suave_metacontrol/suave_metacontrol/random_reasoner.py

randomly adapting serves as a good baseline for evaluation

Random Adaptation manager

---

suave/config/suave_modes.yaml
suave/launch/const_distance_mission_no_adapt.launch.py
suave/launch/time_constrained_mission_no_adapt.launch.py
suave/suave/const_dist_mission_no_adapt.py
suave/suave/follow_pipeline_lc.py
suave/suave/recover_thrusters_lc.py
suave/suave/time_constrained_mission_no_adapt.py
suave_metacontrol/config/suave.owl
suave_metacontrol/suave_metacontrol/const_dist_mission.py
suave_metacontrol/suave_metacontrol/random_reasoner.py
suave_metacontrol/suave_metacontrol/time_constrained_mission.py

Rename inspect_pipeline to follow_pipeline, and control_motion to maintain_motion to be consistent with the paper
Closes #108 
FYI @EGAlberts @jeroenzwan

💬 rename inspect_pipeline and control_motion

---

.gitignore
docker/runner/runner.sh
docker/runner/scripts/launch_mission.sh
docker/runner/scripts/launch_sim.sh
docker/runner/scripts/start_ardusub.sh
suave/launch/suave.launch.py
suave/suave/follow_pipeline_lc.py
suave/suave/spiral_search_lc.py
suave_metacontrol/launch/suave_metacontrol.launch.py
suave_missions/config/mission_config.yaml
suave_missions/launch/mission.launch.py
suave_missions/suave_missions/const_dist_mission.py
suave_missions/suave_missions/mission_planner.py
suave_missions/suave_missions/time_constrained_mission.py

Now it should be possible to run the missions in batch.

Updates to runner and launch

---

README.md
suave_metacontrol/launch/suave_metacontrol.launch.py

Sorry for being lazy and not listing all changes haha...

Updated README with things discussed in meeting.

---

.gitignore
README.md
docker/patch/dockerfile
docker/patch/patch.sh
docker/patch/vnc_startup.sh
docker/runner/runner.sh
suave/launch/suave.launch.py
suave/suave/spiral_search_lc.py
suave_metacontrol/launch/suave_metacontrol.launch.py
suave_metacontrol/launch/suave_random.launch.py
suave_metacontrol/suave_metacontrol/random_reasoner.py
suave_missions/config/mission_config.yaml
suave_missions/results/seams2023_mission_config.yaml
suave_missions/results/seams2023_results.csv
suave_missions/suave_missions/time_constrained_mission.py

Seams submission version.
Includes: bug fix, changes to launchfiles, results, and docker patch

Seams submission version

---

README.md
suave/launch/simulation.launch.py
suave/suave.rosinstall
suave_metacontrol/package.xml

Update mavros version and launchfile

Update mavros version and launchfile

---

README.md
docs/source/run.md

I updated the readme and documentation to reflect the correct path to run the "runner" script

correct path to runner script

---

suave.rosinstall

⬆️ Upgrade metacontrol version

⬆️ Upgrade metacontrol version

---

suave_managing/suave_bt/include/suave_bt/action_recharge_battery.hpp
suave_managing/suave_bt/src/suave_bt/action_recharge_battery.cpp
suave_managing/suave_bt/src/suave_bt/suave_mission.cpp
suave_metrics/suave_metrics/mission_metrics.py
suave_missions/config/mission_config.yaml
suave_monitor/suave_monitor/battery_monitor.py

Add reaction time for battery and fix but in suave_bt

Reaction time
